name: LEVWORTSMP
main: NurAzliYT\LEVWORTSMP\LEVWORTSMP
api: 5.0.0
version: 1.0.0
author: NurAzliYT
description: "Server Menu LevwortSMP"

commands:
lsmp:
permission: levwortsmp.command

permissions:
levwortsmp.command:
default: op
